version: 0.0
os: linux
files:
  - source: /target/*.jar
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 60
      runas: ubuntu
    - location: scripts/start_server
      timeout: 60
      runas: ubuntu