version: 0.0
os: linux
files:
  - source: /target/*.jar
    destination: /logostory/orderbook
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 10
      runas: root
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 10
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 10
      runas: root