spring:
  datasource:
    url: jdbc:mysql://logostory.c5p91wjpe5yl.ap-northeast-2.rds.amazonaws.com/orderbook_dev?useSSL=false
    username: orderbook
    password: orderbook
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    encoding: UTF-8
    clean-on-validation-error: false
  logging:
    level:
      org:
        hibernate:
          type: debug
